import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home(props) {
  const [blog,setBlog] = useState(props.allBlogs)
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <main className={styles.main}>
        <div className={styles.imgrap}>
    <Image className={styles.myimg} src="/home.jpg" alt="" srcSet="" width={237} height={158}/>

        </div>
        <h1 className={styles.title}>
          &lt;Hunting Coder/&gt;
        </h1>
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>

        <div className={styles.blog}>
          <h2>Latest Blogs</h2>
          {blog.map((blogitem)=>{
            return <div className={styles.blogItem} key={blogitem.slug}>
            <Link href={`/blogpost/${blogitem.slug}`}><h3>{blogitem.title}</h3></Link>
            <p>{blogitem.content.substr(0,145)}...</p>
             </div>
          })}
        </div>
      </main>

      
    </div>
  )
}
export async function getServerSideProps(context){
  let data = await fetch("http://localhost:3000/api/blogs?count=3");
  let allBlogs = await data.json();
  return {
    props: {allBlogs},
  }
}
